# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
      - uses: TickX/var-to-dotenv@v1.1.1
      with:
        key: 'SOME_API_URI' # [Required]
        value: ${{secrets.firebaseConfig}} # [Required]
        default: 'https://api.alt.com' # [Optional] if `value` is empty, this is used instead
        nullable: 'false' # [Optional] if the resolved value is empty, the variable will be omitted
        envPath: '.env' # [Optional] The path to the dotenv file (defaults to `.env`)
    - run: npm install
    - run: npm run test
    - run: npm run build